### ISSUE TITLE
Link loses context with Immutable seq iterable?

### ISSUE THREAD

**Issue by kentor** [rackt/react-router#1074]
I'm not too familiar with contexts. I'm using the new feature in React 0.13 where we can use an iterable instead of an array in JSX. Only problem is that it seems like `Link` loses the context when it is returned in a mapped sequence:

```javascript
var Router = ReactRouter;
var { Link, Route } = Router;

var data = Immutable.OrderedSet([1]);

var App = React.createClass({
  render() {
    return (
      <div>
        {data.toSeq().map(v => (
          <Link to="test" key={v}>{v}</Link>
        ))}
      </div>
    );
  }
});

var routes = (
  <Route handler={App}>
    <Route handler={App} name="test" />
  </Route>
);

Router.run(routes, (Handler) => {
  React.render(<Handler />, document.getElementById('app'));
});
```

```
error TypeError: Cannot read property 'makeHref' of undefined
    at Link.getHref (http://cdnjs.cloudflare.com/ajax/libs/react-router/0.13.2/ReactRouter.js:217:36)
    at Link.render (http://cdnjs.cloudflare.com/ajax/libs/react-router/0.13.2/ReactRouter.js:243:23)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (http://cdnjs.cloudflare.com/ajax/libs/react/0.13.1/react.js:6925:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (http://cdnjs.cloudflare.com/ajax/libs/react/0.13.1/react.js:6951:14)
```

If I convert the sequence to an array:
```javascript
        {data.toSeq().map(v => (
          <Link to="test" key={v}>{v}</Link>
        )).toArray()}
```
it'll work again.

JSBin: http://jsbin.com/picugu/3/edit?html,js,output

It might have something to do with sequences being lazy. If I use `cacheResult()` on the sequence that'll also work..

**Comment by ryanflorence** [comment]
perhaps this is a bug for react itself... let me know if there's something we can do though to make it better.

**Comment by berus97** [comment]
Perhaps is problem of Immutable library.
Workaround for me in another project is transform Seq to array.

data.toSeq().toArray().map(v =>
