### ISSUE TITLE
Run examples on windows

### ISSUE THREAD

**Issue by halldorbjarni** [rackt/react-router#1168]
I have to rename scripts/build.sh to scripts/builds.bat, delete the shebang line and modify package.json to execute the build script with bash as such ```"build": "bash scripts/build.bat",```. Maybe there is some easier way so Windows user can run the examples? Also,  **Auth flow** example seems to fail on Windows with the following error when I run ```npm run examples```,  all other examples run fine:

``` javascript                                                                                                                                 
ERROR in ./examples/auth-flow/app.js                                                                                                            
Module build failed: SyntaxError: C:/Users/LAKHBT/react-router/examples/auth-flow/app.js: Line 7: 'this' is not allowed before super()          
   5 | class App extends React.Component {                                                                                                      
   6 |   constructor () {                                                                                                                       
>  7 |     this.state = {                                                                                                                       
     |     ^                                                                                                                                    
   8 |       loggedIn: auth.loggedIn()                                                                                                          
   9 |     };                                                                                                                                   
  10 |   }                                                                                                                                      
    at TraversalPath.errorWithNode (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\traversal\path\index.js:449:15)              
    at TraversalPath.enter (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\transformation\transformers\es6\classes.js:138:20)   
    at TraversalPath.call (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\traversal\path\index.js:740:28)                       
    at TraversalPath.visit (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\traversal\path\index.js:764:10)                      
    at TraversalContext.visitSingle (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\traversal\context.js:72:41)                 
    at TraversalContext.visit (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\traversal\context.js:82:19)                       
    at Function.traverse.node (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\traversal\index.js:59:17)                         
    at TraversalPath.visit (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\traversal\path\index.js:781:31)                      
    at TraversalContext.visitSingle (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\traversal\context.js:72:41)                 
    at TraversalContext.visit (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\traversal\context.js:82:19)                       
    at Function.traverse.node (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\traversal\index.js:59:17)                         
    at TraversalPath.visit (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\traversal\path\index.js:781:31)                      
    at TraversalContext.visitSingle (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\traversal\context.js:72:41)                 
    at TraversalContext.visit (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\traversal\context.js:82:19)                       
    at Function.traverse.node (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\traversal\index.js:59:17)                         
    at TraversalPath.visit (C:\Users\LAKHBT\react-router\node_modules\babel-core\lib\babel\traversal\path\index.js:781:31)          
```

**Comment by mjackson** [comment]
@halldorbjarni Thanks for the heads up. I'm a total beginner when it comes to working on Windows these days. But we can't be the first project that has run into this problem. What do other people do?

**Comment by taurose** [comment]
I've never tried building on windows, but `npm run examples` has been working fine for me. The error you mentioned should be gone by now (I had to `npm i babel-loader` to get it, so it's probably not platform-related).

**Comment by halldorbjarni** [comment]
One option for making the build process cross platform is  [node-gyp](https://github.com/TooTallNate/node-gyp). I've never used it myself but will happily try to create a fix for this.

**Comment by ryanflorence** [comment]
if I checkout 0.13.3 on mac its broken too, we just have a busted example, try latest master, I'm pretty sure it'll work on windows.
