### ISSUE TITLE
can't run examples

### ISSUE THREAD

**Issue by p2227** [rackt/react-router#1276]
when i run `npm run examples` it cant work,here is the log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'examples' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink D:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'preexamples', 'examples', 'postexamples' ]
6 info preexamples react-router@0.13.3
7 info examples react-router@0.13.3
8 verbose unsafe-perm in lifecycle true
9 info react-router@0.13.3 Failed to exec examples script
10 verbose stack Error: react-router@0.13.3 examples: `webpack-dev-server --config examples/webpack.config.js --content-base examples`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid react-router@0.13.3
12 verbose cwd D:\Program\git\react-router
13 error Windows_NT 6.1.7601
14 error argv "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "examples"
15 error node v0.12.2
16 error npm  v2.7.4
17 error code ELIFECYCLE
18 error react-router@0.13.3 examples: `webpack-dev-server --config examples/webpack.config.js --content-base examples`
18 error Exit status 1
19 error Failed at the react-router@0.13.3 examples script 'webpack-dev-server --config examples/webpack.config.js --content-base examples'.
19 error This is most likely a problem with the react-router package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     webpack-dev-server --config examples/webpack.config.js --content-base examples
19 error You can get their info via:
19 error     npm owner ls react-router
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

```

**Comment by mjackson** [comment]
Did you run an `npm install` first?

**Comment by p2227** [comment]
> Did you run an npm install first?

i did it . but `build.sh` can't run in window environment

**Comment by frg** [comment]
#1229 helped me get "npm install" to work but I cant get "npm run examples" to work.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'examples' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'preexamples', 'examples', 'postexamples' ]
6 info preexamples react-router@1.0.0-beta3
7 info examples react-router@1.0.0-beta3
8 verbose unsafe-perm in lifecycle true
9 info react-router@1.0.0-beta3 Failed to exec examples script
10 verbose stack Error: react-router@1.0.0-beta3 examples: `webpack-dev-server --config examples/webpack.config.js --content-base examples --inline`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid react-router@1.0.0-beta3
12 verbose cwd C:\sauce\examples\react\react-router
13 error Windows_NT 6.3.9600
14 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "examples"
15 error node v0.12.2
16 error npm  v2.7.4
17 error code ELIFECYCLE
18 error react-router@1.0.0-beta3 examples: `webpack-dev-server --config examples/webpack.config.js --content-base examples --inline`
18 error Exit status 1
19 error Failed at the react-router@1.0.0-beta3 examples script 'webpack-dev-server --config examples/webpack.config.js --content-base examples --inline'.
19 error This is most likely a problem with the react-router package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     webpack-dev-server --config examples/webpack.config.js --content-base examples --inline
19 error You can get their info via:
19 error     npm owner ls react-router
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```
