### ISSUE TITLE
navigator is not defined - running react router on server

### ISSUE THREAD

**Issue by michaelBenin** [rackt/react-router#1316]
```
Debugger listening on port 5858
/Users/michaelbenin/Projects/express-react-isomorphic-fastboot/node_modules/react-router/lib/DOMUtils.js:50
  var ua = navigator.userAgent;
           ^
ReferenceError: navigator is not defined
    at supportsHistory (/Users/michaelbenin/Projects/express-react-isomorphic-fastboot/node_modules/react-router/lib/DOMUtils.js:50:12)
    at new BrowserHistory (/Users/michaelbenin/Projects/express-react-isomorphic-fastboot/node_modules/react-router/lib/BrowserHistory.js:52:54)
    at Object.<anonymous> (/Users/michaelbenin/Projects/express-react-isomorphic-fastboot/node_modules/react-router/lib/BrowserHistory.js:148:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/michaelbenin/Projects/express-react-isomorphic-fastboot/build/react_router/react_router.js:17:37)

```

**Comment by ryanflorence** [comment]
we might still need to work out some things with server rendering on the master branch, but your log indicates you're using `BrowserHistory`, instead you need to create a location on the server `var location = new Location(req.path, req.query);`

https://rackt.github.io/react-router/tags/v1.0.0-beta1.html#Server Rendering

**Comment by omerts** [comment]
@ryanflorence  creating just a location without the history, throws an invariant error, and throughout the app it always refreshes the page
