### ISSUE TITLE
Error when rendering on server

### ISSUE THREAD

**Issue by xpepermint** [rackt/react-router#1361]
I'm playing with `1.0.0-beta2`. I think I did exactly as described here: https://github.com/rackt/react-router/blob/master/doc/00%20Guides/Server%20Rendering.md.

```js
import React from 'react';
import Router from 'react-router';
import Location from 'react-router/lib/Location';

let routes = require('./routes');

export default (req, res) => {

  var location = new Location(req.path, req.query);

  Router.run(routes, location, (error, state, transition) => {
    var html = React.renderToString(<Router {...state}/>);
    res.render('index', { html });
  });
};
```

The rendered `html` content looks ok but I see an error in my server console.

```
Error: Invariant Violation: Server-side <Router>s need location, branch, params, and components props. Try using Router.run to get all the props you need
    at invariant (/Users/me/Downloads/myapp/node_modules/react-router/node_modules/invariant/invariant.js:44:15)
    at [object Object].componentWillMount (/Users/me/Downloads/myapp/node_modules/react-router/lib/Router.js:254:34)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/me/Downloads/myapp/node_modules/react/lib/ReactCompositeComponent.js:228:14)
    at [object Object].wrapper [as mountComponent] (/Users/me/Downloads/myapp/node_modules/react/lib/ReactPerf.js:70:21)
    at /Users/me/Downloads/myapp/node_modules/react/lib/ReactServerRendering.js:42:27
    at ReactServerRenderingTransaction.Mixin.perform (/Users/me/Downloads/myapp/node_modules/react/lib/Transaction.js:134:20)
    at Object.renderToString (/Users/me/Downloads/myapp/node_modules/react/lib/ReactServerRendering.js:39:24)
    at /Users/me/Downloads/myapp/app/server.js:12:22
    at /Users/me/Downloads/myapp/node_modules/react-router/lib/Router.js:53:7
    at done (/Users/me/Downloads/myapp/node_modules/react-router/lib/AsyncUtils.js:14:14)
```

**Comment by xpepermint** [comment]
Lol. The error is gone after I added `favicon.ico` to my public directory :). My mistake, closing ...
