### ISSUE TITLE
willTransitionTo and transition(...) fails on server side

### ISSUE THREAD

**Issue by alekbarszczewski** [rackt/react-router#1372]
Using `react-router#0.13.3` and `react#0.13.3`

routes:

```html
<Route path="/" handler={App}>
    <DefaultRoute handler={Home} />
    <NotFoundRoute handler={NotFound} />
    <Route name="home" path="/" handler={Home} />
    <Route handler={Authorized}>
      <Route name="account" path="/account" handler={Account} />
    </Route>
</Route>
```

`Authorized` handler:
```
{RouteHandler} = ReactRouter
module.exports = React.createClass
  statics:
    willTransitionTo: (transition) ->
      transition.redirect('/')
  render: ->
    <RouteHandler />
```

rendering function:
```
(req, res, next) ->
  ReactRouter.run routes, req.path, (Root, state) ->
    reactHtml = React.renderToString(<Root />)
```

1. Without server-side rendering app works as expected `/account` is redirected to `/`
2. With server-side rendering when I load `/` initially and then click a link which redirects to `/account` then it works as expected (I am redirected back to `/`)
3. With server-side rendering when I load `/account` initially then following error is thrown:

```
Error: Unhandled aborted transition! Reason: [object Object]
  at Function.React.createClass.statics.handleAbort (/Users/alek/Desktop/react-boilerplate/node_modules/react-router/lib/createRouter.js:262:55)
  at Function.dispatchHandler (/Users/alek/Desktop/react-boilerplate/node_modules/react-router/lib/createRouter.js:379:20)
  at /Users/alek/Desktop/react-boilerplate/node_modules/react-router/lib/createRouter.js:349:29
  at /Users/alek/Desktop/react-boilerplate/node_modules/react-router/lib/Transition.js:58:9
  at /Users/alek/Desktop/react-boilerplate/node_modules/react-router/lib/Transition.js:64:41
  at /Users/alek/Desktop/react-boilerplate/node_modules/react-router/lib/Transition.js:69:9
  at Function.Transition.to (/Users/alek/Desktop/react-boilerplate/node_modules/react-router/lib/Transition.js:72:15)
  at /Users/alek/Desktop/react-boilerplate/node_modules/react-router/lib/createRouter.js:348:22
  at Function.Transition.from (/Users/alek/Desktop/react-boilerplate/node_modules/react-router/lib/Transition.js:51:15)
  at Function.dispatch (/Users/alek/Desktop/react-boilerplate/node_modules/react-router/lib/createRouter.js:345:20)
  at Function.refresh (/Users/alek/Desktop/react-boilerplate/node_modules/react-router/lib/createRouter.js:396:16)
  at Function.run (/Users/alek/Desktop/react-boilerplate/node_modules/react-router/lib/createRouter.js:392:16)
  at Object.runRouter [as run] (/Users/alek/Desktop/react-boilerplate/node_modules/react-router/lib/runRouter.js:45:10)
  at module.exports (/Users/alek/Desktop/react-boilerplate/server/render.cjsx:9:15)
  at Layer.handle [as handle_request] (/Users/alek/Desktop/react-boilerplate/node_modules/express/lib/router/layer.js:82:5)
  at next (/Users/alek/Desktop/react-boilerplate/node_modules/express/lib/router/route.js:110:13)
  at Route.dispatch (/Users/alek/Desktop/react-boilerplate/node_modules/express/lib/router/route.js:91:3)
  at Layer.handle [as handle_request] (/Users/alek/Desktop/react-boilerplate/node_modules/express/lib/router/layer.js:82:5)
  at /Users/alek/Desktop/react-boilerplate/node_modules/express/lib/router/index.js:267:22
  at Function.proto.process_params (/Users/alek/Desktop/react-boilerplate/node_modules/express/lib/router/index.js:321:12)
  at next (/Users/alek/Desktop/react-boilerplate/node_modules/express/lib/router/index.js:261:10)
  at SendStream.error (/Users/alek/Desktop/react-boilerplate/node_modules/express/node_modules/serve-static/index.js:107:7)
  at SendStream.emit (events.js:95:17)
  at SendStream.error (/Users/alek/Desktop/react-boilerplate/node_modules/express/node_modules/send/index.js:250:17)
  at SendStream.onStatError (/Users/alek/Desktop/react-boilerplate/node_modules/express/node_modules/send/index.js:346:48)
  at next (/Users/alek/Desktop/react-boilerplate/node_modules/express/node_modules/send/index.js:606:16)
  at onstat (/Users/alek/Desktop/react-boilerplate/node_modules/express/node_modules/send/index.js:595:14)
  at Object.oncomplete (fs.js:107:15)
```

What I can do about it? How to transition on server side? The use case is that user may hit url that requires authorization but no cookie with session id (for example) is provided - then I want to redirect him...

**Comment by alekbarszczewski** [comment]
I guess `willTransitionTo` will be removed in 1.x.x, so I am closing this
