### ISSUE TITLE
Server Rendering example not working, using v1.0.0-beta2 

### ISSUE THREAD

**Issue by eriknyk** [rackt/react-router#1409]
Hi, 
I'm trying to use the server side example documented here: https://github.com/rackt/react-router/blob/master/doc/00%20Guides/Server%20Rendering.md

but I'm getting an error.

```
TypeError: undefined is not a function
    at /Users/erik/test/flux-examples/react-router/server.js:27:12
    at Layer.handle [as handle_request] (/Users/erik/test/flux-examples/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/erik/test/flux-examples/node_modules/express/lib/router/index.js:312:13)
    at /Users/erik/test/flux-examples/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/erik/test/flux-examples/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/erik/test/flux-examples/node_modules/express/lib/router/index.js:271:10)
    at favicon (/Users/erik/test/flux-examples/node_modules/serve-favicon/index.js:72:7)
    at Layer.handle [as handle_request] (/Users/erik/test/flux-examples/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/erik/test/flux-examples/node_modules/express/lib/router/index.js:312:13)
    at /Users/erik/test/flux-examples/node_modules/express/lib/router/index.js:280:7
```

and my line: 27 is 
```
    Router.run(app.getComponent(), req.path, function (Handler, state) {
```

the complete implementation is:

```
require('babel/register');
var express = require('express');
var favicon = require('serve-favicon');
var serialize = require('serialize-javascript');
var navigateAction = require('./actions/navigate');
var debug = require('debug')('Example');
var React = require('react');
var app = require('./app');
var HtmlComponent = React.createFactory(require('./components/Html.jsx'));
var FluxibleComponent = require('fluxible/addons/FluxibleComponent');
var Router = require('react-router');

var server = express();
server.use(favicon(__dirname + '/../favicon.ico'));
server.use('/public', express.static(__dirname + '/build'));

server.use(function (req, res, next) {
    var context = app.createContext();

    debug('Executing navigate action');
    Router.run(app.getComponent(), req.path, function (Handler, state) {
        context.executeAction(navigateAction, state, function () {
            debug('Exposing context state');
            var exposed = 'window.App=' + serialize(app.dehydrate(context)) + ';';

            debug('Rendering Application component into html');
            var Component = React.createFactory(Handler);
            var html = React.renderToStaticMarkup(HtmlComponent({
                state: exposed,
                markup: React.renderToString(
                    React.createElement(
                        FluxibleComponent,
                        { context: context.getComponentContext() },
                        Component()
                    )
                )
            }));

            debug('Sending markup');
            res.send(html);
        });
    });
});

var port = process.env.PORT || 3000;
```

And basically it means that  run() method of Router object undefined.

I'm using ver 1.0.0-beta2

Best regards

**Comment by heebtob** [comment]
try it with
``` javascript
var location = new Location(req.path, req.query);
Router.run(app.getComponent(), location, (error, initialState, transition) => {
```
and instead of Component()
``` javascript
<Router {...initialState}/>
```

**Comment by eriknyk** [comment]
thanks @heebtob, 
but the initial problem is that 

```
var Router = require('react-router');
```
is returning  https://github.com/rackt/react-router/blob/master/modules/index.js

and it is a Router object https://github.com/rackt/react-router/blob/master/modules/Router.js

that have not the method run()


Regards.

**Comment by heebtob** [comment]
https://github.com/rackt/react-router/blob/master/modules/Router.js 
line 65
``` JavaScript
run(routes, location, transitionHooks, callback) {
```

**Comment by tmbtech** [comment]
I think if you are using `require` instead of ES6 `import`, you have to ask for the default. 
try
`var Router = require('react-router').default;` 

https://github.com/rackt/react-router/issues/1370

**Comment by eriknyk** [comment]
thanks @tmbtech

**Comment by ckahle33** [comment]
thanks @tmbtech - this should be mentioned in the docs somewhere..
