### ISSUE TITLE
0.13.3 with server-side rendering and nesting doesn't work

### ISSUE THREAD

**Issue by timsuchanek** [rackt/react-router#1665]
Hi, I already got server side rendering working with react-router `0.11.6` and react `0.12.2`.

This is the code of the routes:
```js

var Routes = (
	<Route handler={App}>
		<Route name="home" path="/" handler={Home} />
	</Route>
);
```

But now when I upgrade both to `0.13.3`, I get the following Error:

```sh
TypeError: Cannot read property 'getRouteAtDepth' of undefined
    at RouteHandler.createChildRouteHandler (node_modules/react-router/lib/components/RouteHandler.js:67:38)
    at RouteHandler.render (node_modules/react-router/lib/components/RouteHandler.js:82:26)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (server/page.generated.js:11834:35)
    at ReactCompositeComponentMixin._renderValidatedComponent (server/page.generated.js:11861:15)
    at wrapper [as _renderValidatedComponent] (server/page.generated.js:871:22)
    at ReactCompositeComponentMixin.mountComponent (server/page.generated.js:11282:31)
    at wrapper [as mountComponent] (server/page.generated.js:871:22)
    at Object.ReactReconciler.mountComponent (server/page.generated.js:945:36)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (server/page.generated.js:12833:45)
    at ReactDOMComponent.Mixin._createContentMarkup (server/page.generated.js:12418:33)
```

I have no Idea what the problem is, in the [0.11 to 0.12/0.13 migration guide](https://github.com/rackt/react-router/blob/0.13.x/UPGRADE_GUIDE.md) there I don't see anything related.

Here I created a minimal test case that you can run to reproduce the issue:
https://github.com/timsuchanek/react-router-test

Thanks!

[Update 1]:
I looked a littlebit into the code and found that `RouteHandler` wants to access the parent context. I think the parent context is set in https://github.com/rackt/react-router/blob/57543eb41ce45b994a29792d77c86cc10b51eac9/modules/createRouter.js#L528
But not found. I have no single Idea why the context is undefined here, but sth. with the contexts is broken.

**Comment by ryanflorence** [comment]
you need to upgrade react to 0.13 as well.

**Comment by timsuchanek** [comment]
Yes, react has version 0.13.3 as well as you  an see in the example [here](https://github.com/timsuchanek/react-router-test). 
![screen shot 2015-08-19 at 12 51 10](https://cloud.githubusercontent.com/assets/1094804/9354478/f8b6ce5c-4670-11e5-99f8-55857d826389.png)

But it still doesn't work...

**Comment by hyusetiawan** [comment]
I am having the same issue and there are not multiple versions of react as well.
