### ISSUE TITLE
1.0.0-beta3 - Server side rending error: Document is not defined

### ISSUE THREAD

**Issue by ostrgard** [rackt/react-router#1667]
Hello!

I'm getting this error on my server when sending it a get request: `ReferenceError: document is not defined`. Full stacktrace in the bottom of the post.

If I do `var html = React.renderToString(<div>hello world!</div>);` instead of `var html = React.renderToString(<Router {...initialState}/>);`, I don't get this error and it renders just fine. This leads me to think something is bugging in the router. As it might appear, I've tried to follow [the guide in the 1.0.0-beta docs](https://github.com/rackt/react-router/blob/master/doc/00%20Guides/Server%20Rendering.md). 

Thanks for looking.

**server.js**
```
import express from 'express';
import React from 'react';
import Router from 'react-router';
import Location from 'react-router/lib/Location';
import routes from '../shared/routes';

const app = express();

app.get('/', function (req, res) {
  var location = new Location(req.path, req.query);
  Router.run(routes, location, (error, initialState, transition) => {
    fetchSomeData(initialState.components, (error, initialData) => {
      var html = React.renderToString(<Router {...initialState}/>);
      res.send(renderFullPage(html, initialData));
    });
  });
});

function fetchSomeData(components, response) {...}
function renderFullPage(html, initialData) {...}
```

**routes.js**
```
import React from 'react';
import Route from 'react-router';
import AppHandler from './components/AppHandler';

export default (
  <Route path="/" component={AppHandler} />
);
```

**AppHandler.js**
```
import React from 'react';

export default class AppHandler extends React.Component {
  render() {
    return <div>Hello App Handler</div>;
  }
}
```

**Full stacktrace**
```
ReferenceError: document is not defined
   at getActiveElement (/Users/soren/Documents/Git/aarhus-business-college-node/node_modules/react-router/node_modules/react/lib/getActiveElement.js:23:12)
   at ReactReconcileTransaction.ReactInputSelection.getSelectionInformation (/Users/soren/Documents/Git/aarhus-business-college-node/node_modules/react-router/node_modules/react/lib/ReactInputSelection.js:40:23)
   at ReactReconcileTransaction.Mixin.initializeAll (/Users/soren/Documents/Git/aarhus-business-college-node/node_modules/react-router/node_modules/react/lib/Transaction.js:168:30)
   at ReactReconcileTransaction.Mixin.perform (/Users/soren/Documents/Git/aarhus-business-college-node/node_modules/react-router/node_modules/react/lib/Transaction.js:133:12)
   at ReactUpdatesFlushTransaction.Mixin.perform (/Users/soren/Documents/Git/aarhus-business-college-node/node_modules/react-router/node_modules/react/lib/Transaction.js:134:20)
   at ReactUpdatesFlushTransaction.assign.perform (/Users/soren/Documents/Git/aarhus-business-college-node/node_modules/react-router/node_modules/react/lib/ReactUpdates.js:95:38)
   at Object.flushBatchedUpdates (/Users/soren/Documents/Git/aarhus-business-college-node/node_modules/react-router/node_modules/react/lib/ReactUpdates.js:175:19)
   at Object.wrapper [as flushBatchedUpdates] (/Users/soren/Documents/Git/aarhus-business-college-node/node_modules/react-router/node_modules/react/lib/ReactPerf.js:70:21)
   at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/soren/Documents/Git/aarhus-business-college-node/node_modules/react-router/node_modules/react/lib/Transaction.js:207:25)
   at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/soren/Documents/Git/aarhus-business-college-node/node_modules/react-router/node_modules/react/lib/Transaction.js:148:16)
```

**Comment by ryanflorence** [comment]
hmm, there's a test that doesn't have this problem, have you tried beta3?

https://github.com/rackt/react-router/blob/master/modules/__tests__/serverRendering-test.js
