### ISSUE TITLE
1.0.0-beta-3 - window is not defined

### ISSUE THREAD

**Issue by Dharmoslap** [rackt/react-router#1708]
I want to use React Router1.0.0-beta-3 for server side rendering, but I've got this:

node_modules/react-router/lib/DOMUtils.js:52
return window.history && 'pushState' in window.history;
ReferenceError: window is not defined

**Comment by dozoisch** [comment]
How are you defining your routes for server-side rendering?

**Comment by Dharmoslap** [comment]
ReferenceError: window is not defined
    at supportsHistory (/Volumes/Workspace/Skypicker/repos/Skypicker/node_modules/react-router/lib/DOMUtils.js:52:9)
    at new BrowserHistory (/Volumes/Workspace/Skypicker/repos/Skypicker/node_modules/react-router/lib/BrowserHistory.js:46:54)
    at Object.<anonymous> (/Volumes/Workspace/Skypicker/repos/Skypicker/node_modules/react-router/lib/BrowserHistory.js:132:15)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.cls_wrapMethod [as _load] (/Volumes/Workspace/Skypicker/repos/Skypicker/node_modules/newrelic/lib/shimmer.js:208:38)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by Dharmoslap** [comment]
I'm defining the router pretty much like it's described here http://rackt.github.io/react-router/tags/v1.0.0-beta3.html#Server Rendering

**Comment by dozoisch** [comment]
Seems like you are using BrowserHistory on the server. This will not work as you are not in a browser. \

On the server, in the example they do not define an history at all. They use a "static" location. to do the render

```
// server.js
import Router from 'react-router';
import Location from 'react-router/lib/Location';
let action = (req, res) => {
  var location = new Location(req.path, req.query);

  Router.run(routes, location, (error, initialState, transition) => {
   // ....
      var html = React.renderToString(
        <Router {...initialState}/>
      );
```

could that be the culprit?
