### ISSUE TITLE
Missing information at server rendering docs at version 1.0.0 - beta 3

### ISSUE THREAD

**Issue by erickbelfy** [rackt/react-router#1732]
I am trying to follow the server rendering example at [here](https://github.com/rackt/react-router/blob/v1.0.0-beta3/doc/00%20Guides/Server%20Rendering.md) but i think it misses some code at `<Router {...initialState}/>` line. When i try to render this on server side my sever raise this exception:
```
Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).
Warning: Only functions or strings can be mounted as React components.
TypeError: Cannot read property 'toUpperCase' of undefined
    at autoGenerateWrapperClass (/Users/erickbelfort/eighty6/supernova/supernova-admin/node_modules/react/lib/ReactDefaultInjection.js:53:18)
    at Object.getComponentClassForElement (/Users/erickbelfort/eighty6/supernova/supernova-admin/node_modules/react/lib/ReactNativeComponent.js:59:49)
    at ReactCompositeComponentMixin._processProps (/Users/erickbelfort/eighty6/supernova/supernova-admin/node_modules/react/lib/ReactCompositeComponent.js:429:44)
    at ReactCompositeComponentMixin.mountComponent (/Users/erickbelfort/eighty6/supernova/supernova-admin/node_modules/react/lib/ReactCompositeComponent.js:127:28)
    at wrapper [as mountComponent] (/Users/erickbelfort/eighty6/supernova/supernova-admin/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/erickbelfort/eighty6/supernova/supernova-admin/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/erickbelfort/eighty6/supernova/supernova-admin/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/erickbelfort/eighty6/supernova/supernova-admin/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/erickbelfort/eighty6/supernova/supernova-admin/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/Users/erickbelfort/eighty6/supernova/supernova-admin/node_modules/react/lib/ReactReconciler.js:38:35)
```

**Comment by erickbelfy** [comment]
`server.js`
```
import express from "express";
import React from "react";
import { Router } from "react-router";
import Location from 'react-router/lib/Location';
import routes from '../shared/routes';
const app = express();

//jade just for index view
app.get('/favicon.ico', (req, res) => res.send(''));
app.set('views', './views');
app.set('view engine', 'jade');
app.use((req, res) => {
    var location = new Location(req.path, req.query);
    Router.run(routes, location, (error, initialState, transition) => {
        console.log(initialState);
        let content = React.renderToString(<Router {...initialState} />);
        console.log(content);
        res.send('index', {content: content});
    });
});

var server = app.listen(3000, function () {
    var host = server.address().address;
    var port = server.address().port;
    console.log('Listening at http://%s:%s', host, port);
});
````
`client.js`
```
import React from "react";
import { Router } from "react-router";
import { BrowserHistory } from 'react-router/lib/BrowserHistory';
import routes from "../shared/routes";
import LoginActions from '../shared/login/LoginActions';


let token = localStorage.getItem('token');
if (token) {
    LoginActions.loginUser(token);
}

React.render(<Router history={BrowserHistory} children={routes} />, document.getElementById('app'));

```

**Comment by ryanflorence** [comment]
this API isn't in the code yet, but will be today/tomorrow: https://github.com/rackt/react-router/blob/master/docs/ServerRendering.md

**Comment by liygheart** [comment]
@ryanflorence  https://github.com/rackt/react-router/blob/master/docs/ServerRendering.md

this link open fail

**Comment by prattsj** [comment]
All docs are here:
https://github.com/rackt/react-router/tree/master/docs

Browse around to find what ya need.
