### ISSUE TITLE
run examples issue

### ISSUE THREAD

**Issue by Synturas** [rackt/react-router#1740]
```
ERROR in ./examples/auth-flow/app.js
Module build failed: SyntaxError: /tmp/react-router/examples/auth-flow/app.js: Line 7: 'this' is not allowed before super()
   5 | class App extends React.Component {
   6 |   constructor () {
>  7 |     this.state = {
     |     ^
   8 |       loggedIn: auth.loggedIn()
   9 |     };
  10 |   }
    at File.errorWithNode (/tmp/react-router/node_modules/babel-core/lib/transformation/file/index.js:488:13)
    at NodePath.errorWithNode (/tmp/react-router/node_modules/babel-core/lib/traversal/path/index.js:155:26)
    at NodePath.ThisExpression (/tmp/react-router/node_modules/babel-core/lib/transformation/transformers/es6/classes/vanilla.js:132:20)
    at NodePath.call (/tmp/react-router/node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (/tmp/react-router/node_modules/babel-core/lib/traversal/path/context.js:89:8)
    at TraversalContext.visitSingle (/tmp/react-router/node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (/tmp/react-router/node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (/tmp/react-router/node_modules/babel-core/lib/traversal/index.js:76:17)
    at NodePath.visit (/tmp/react-router/node_modules/babel-core/lib/traversal/path/context.js:106:26)
    at TraversalContext.visitSingle (/tmp/react-router/node_modules/babel-core/lib/traversal/context.js:132:12)
    at TraversalContext.visit (/tmp/react-router/node_modules/babel-core/lib/traversal/context.js:148:19)
    at Function.traverse.node (/tmp/react-router/node_modules/babel-core/lib/traversal/index.js:76:17)
webpack: bundle is now VALID.
```

This happens when i try to run ```npm run examples``` on Fedora, does anyone know what I can do about this ?

**Comment by zebapy** [comment]
I'm assuming constructor should look like this ... 

```
constructor(props) {
  super(props);

  this.state = {
    loggedIn: auth.loggedIn()
  }
}
```

I don't have a huge understanding of how the above works but I just know I need to do this to make `this` accessible in my class components :) 

See https://facebook.github.io/react/docs/reusable-components.html#es6-classes

Maybe example is just broken?

**Comment by Synturas** [comment]
So, do i have to prepare the examples ?  The readme just says, npm install, npm run examples, which fails also on OS X Yosemite.

**Comment by adamburmister** [comment]
:+1: Just checked out the 0.13.x branch and had this break.

**Comment by ryanflorence** [comment]
all examples on master should be running, sorry about that.
