### ISSUE TITLE
Lose site of HashHistory on beta4. Where is it?

### ISSUE THREAD

**Issue by axross** [rackt/react-router#1802]
Hi. Thank you I usually use react-router!

I have a question.

I lose site of HashHistory on beta4. Where is it?

```
% node                                                               [18:14:58]
> var history = require('react-router/lib/HashHistory').history;
Error: Cannot find module 'react-router/lib/HashHistory'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:11
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
```

I could not find HashHistory in `node_modules/react-router/lib`.

**Comment by capaj** [comment]
@axross why did you close this? I have the same issue-where is it?

**Comment by gaearon** [comment]
I think `HashLocation` now is used by default so you don't need to specify it.
Instead of `HistoryLocation`, you can use [`createHistory()` from `rackt/history`](https://rackt.github.io/history/v1.8.4/GettingStarted.html).

**Comment by capaj** [comment]
@gaearon thanks, greatly appreaciated. I think I can close the [SO](http://stackoverflow.com/questions/32357359/how-does-webpack-load-a-react-router-lib-hashhistory-or-react-router-lib-browser) question as well.
