### ISSUE TITLE
SSR with history and beta4

### ISSUE THREAD

**Issue by jonjaques** [rackt/react-router#1847]
Hello, 

I'm trying to cook up a simple example of server side rendering with the new APIs introduced on beta4.
I've tried using `useRoutes` from `react-router`, but no matter what I seem to do, I can't get `history.match` to match anything. There also seems to be a problem there, because it warns that no route was matched, but never calls back. 

I've also looked at the docs about [SSR](https://github.com/rackt/react-router/blob/master/docs/ServerRendering.md) from the master branch, however neither the master or `beta4` exports a `match` function.

Any ideas? Am I on the right track, or is this feature not 'ready'?

```
import React, { Component } from 'react'
import { renderToString } from 'react-dom/server';
import { createLocation, createMemoryHistory } from 'history'
import { Route, IndexRoute, RoutingContext, useRoutes } from 'react-router'

// ... components ....

let routes = (
  <Route path="/" component={Master}>
    <IndexRoute component={Test} />
    <Route path="test" component={Test} />
  </Route>
)

router.get('/*', (req, res)=> {
  let location = createLocation(req.url, req.query);
  render(location, (component)=> {
    res.send(renderToString(component))
  })
});

function render(location, callback) {
  let history = useRoutes(createMemoryHistory)({ routes })

  history.match(location, (error, state)=> {
    // never gets here
    callback(<RoutingContext history={history} {...state} />)
  })
}
```

**Comment by jonjaques** [comment]
Update: I've made a bit of progress, in that I can get `history` to see my routes now. Needed to import `createRoutesFromReactChildren`.
```
let routes = createRoutesFromReactChildren(Routes)
let history = useRoutes(createMemoryHistory)({ routes })
```

I believe the last issue I have is that `<RoutingContext />` is not behaving or I'm not passing in the right props.
```
history.match(location, (error, state)=> {
  if (error) {
    return callback(<h1>Error</h1>)
  }
  callback(<RoutingContext history={history} {...state} />)
})
```

When I try to `renderToString`, React throws an error: 
```
Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
    at invariant (/Users/jjaques/Dev/proto/tester/node_modules/react-dom/node_modules/fbjs/lib/invariant.js:39:15)
    at instantiateReactComponent (/Users/jjaques/Dev/proto/tester/node_modules/react-dom/node_modules/react/lib/instantiateReactComponent.js:66:134)
    at instantiateChild (/Users/jjaques/Dev/proto/tester/node_modules/react-dom/node_modules/react/lib/ReactChildReconciler.js:30:28)
    at traverseAllChildrenImpl (/Users/jjaques/Dev/proto/tester/node_modules/react-dom/node_modules/react/lib/traverseAllChildren.js:98:5)
    at traverseAllChildren (/Users/jjaques/Dev/proto/tester/node_modules/react-dom/node_modules/react/lib/traverseAllChildren.js:180:10)
    at Object.ReactChildReconciler.instantiateChildren (/Users/jjaques/Dev/proto/tester/node_modules/react-dom/node_modules/react/lib/ReactChildReconciler.js:53:5)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/jjaques/Dev/proto/tester/node_modules/react-dom/node_modules/react/lib/ReactMultiChild.js:198:43)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/jjaques/Dev/proto/tester/node_modules/react-dom/node_modules/react/lib/ReactDOMComponent.js:541:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/jjaques/Dev/proto/tester/node_modules/react-dom/node_modules/react/lib/ReactDOMComponent.js:438:27)
    at /Users/jjaques/Dev/proto/tester/node_modules/react-dom/node_modules/react/lib/ReactServerRendering.js:42:38
```

Inspecting `RoutingContext` shows the issue.

```
{ type: undefined,
  key: null,
  ref: null,
  _owner: null,
  props:
   { routes: [ [Object], [Object] ],
     params: {},
     location: { pathname: '/', search: '', state: {}, action: 'POP', key: null },
     components: [ [Function: Master], [Function: Test] ] },
  _store: {} }
```

**Comment by jonjaques** [comment]
Well, derp.

RoutingContext isn't available on the `react-router` namespace. Needed to 
```import RoutingContext from 'react-router/lib/RoutingContext'```

**Comment by srph** [comment]
Are you sure it's `RoutingContext`, not `RouteContext`?

**Comment by srph** [comment]
Isn't it an issue that `RoutingContext` isn't available in the namespace?

**Comment by jonjaques** [comment]
Perhaps, but both issues (lack of `match()`, and `RoutingContext`) are fixed in master.

**Comment by srph** [comment]
Probably, gotta check.

> 1.0.0-rc1 released
https://twitter.com/ryanflorence/status/642452530576797696
