### ISSUE TITLE
Uncaught TypeError: Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by hgezim** [rackt/react-router#2011]
I'm seeing this issue as well. Here's the stack trace:

![Stack Trace](https://www.evernote.com/shard/s2/sh/f32fa3a7-9c47-4932-8edb-902dcd9bafd2/6bcc1ac6a106eca6/res/e8988b8a-5b66-4c90-8f58-379f095f76b4/skitch.png)

I think it might concern `react-router` because it starts off from `app.jsx`:

```javascript
// app.jsx
var routes = var routes = (
  <Router history={history}>
    <Route path="/" component={App}>
        <Route path="path1/:action" component={Path1} />
        <Route path="path2/:page/:sortBy/:active" component={Path2} />
        <Route path="path3/:page" component={Path3} />
        <Route path="account" component={Account} />
        <Route path="login" component={Login} />
        <Route path="help" component={Help} />

        <Route path="path4/:kind/:status/:sortBy/:page" component={Path4} ignoreScrollBehavior />
    </Route>
    <Redirect from="/" to="/transfer" params={{"action": "new"}} />
  </Router>
);

React.render( // line 31
  routes, document.getElementById("app")
); // line 33
```

And `App.jsx` line:

```javascript
// App.jsx
  render() {
    const loaded = this.state.accountLoaded && this.state.dataLoaded && this.state.dataTypesLoaded;

    console.log("this.props: ", this.props);
    var children = React.cloneElement(this.props.children, this.props.params); // line 95 **problem line**

   // {children} is rendered in the a return a bit later down here
```

Another stack error here:

```
Unhandled rejection TypeError: Cannot read property '_currentElement' of null
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (node_modules/react/lib/ReactCompositeComponent.js:744:1)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (node_modules/react/lib/ReactCompositeComponent.js:726:1)
    at [object Object].ReactCompositeComponentMixin.updateComponent (node_modules/react/lib/ReactCompositeComponent.js:642:1)
    at [object Object].ReactPerf.measure.wrapper [as updateComponent] (node_modules/react/lib/ReactPerf.js:70:1)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (node_modules/react/lib/ReactCompositeComponent.js:506:1)
    at Object.ReactReconciler.receiveComponent (node_modules/react/lib/ReactReconciler.js:97:1)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (node_modules/react/lib/ReactCompositeComponent.js:748:1)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (node_modules/react/lib/ReactCompositeComponent.js:726:1)
    at [object Object].ReactCompositeComponentMixin.updateComponent (node_modules/react/lib/ReactCompositeComponent.js:642:1)
    at [object Object].ReactPerf.measure.wrapper [as updateComponent] (node_modules/react/lib/ReactPerf.js:70:1)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (node_modules/react/lib/ReactCompositeComponent.js:506:1)
    at Object.ReactReconciler.receiveComponent (node_modules/react/lib/ReactReconciler.js:97:1)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (node_modules/react/lib/ReactCompositeComponent.js:748:1)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (node_modules/react/lib/ReactCompositeComponent.js:726:1)
    at [object Object].ReactCompositeComponentMixin.updateComponent (node_modules/react/lib/ReactCompositeComponent.js:642:1)
    at [object Object].ReactPerf.measure.wrapper [as updateComponent] (node_modules/react/lib/ReactPerf.js:70:1)
```

Related to #1488

**Comment by taurose** [comment]
Seems like `this.props.children` is null, because no child routes are matched. You might want to look into [IndexRoute](https://github.com/rackt/react-router/blob/master/docs/API.md#indexroute) or do a check in `<App>` before using `cloneElement`.

**Comment by CarlosMela** [comment]
Hi, I am upgrading the router from v0.13.3 to v1.0.0-rc1. After doing the changes I got the same error: **Uncaught TypeError: Cannot read property '_currentElement' of null**. I tried with the simplest example I can think of and I get the same error. This issue is closed so I would like to know if I should give up the upgrade for the moment. This is my example:

```javascript
var ReactRouter = require('react-router');
var Router = ReactRouter.Router;
var Route = ReactRouter.Route;
var React = require('React');
var App = React.createClass({
	  render () {
	    return ( <div>App</div> )
	  }
	});
var routes = <Route component={App} path="*"/>;
var AppRouter = <Router routes={routes} onEnter={()=>console.log("Not printed")} />;
React.render(AppRouter, document.getElementById("div"));
```

And here I share part of my package.json, just in case it helps:
```javascript
"dependencies": {
    "flux": "^2.0.3",
    "jquery": "^2.1.4",
    "object-assign": "^1.0.0",
    "react": "^0.13.3",
    "react-bootstrap": "^0.23.7",
    "react-router": "^1.0.0-rc1",
  },
  "devDependencies": {
    "browserify": "^10.1.3",
    "reactify": "^1.1.1",
  },
  "browserify": {
    "transform": [
      [
        "reactify",
        {
          "es6": true
        }
      ]
    ]
  }
```

**Comment by hgezim** [comment]
Thank you, @taurose! That helped greatly.
