### ISSUE TITLE
Building UMD failes, Unknown plugin "object-assign"

### ISSUE THREAD

**Issue by jCalamari** [rackt/react-router#2039]
Trying to build UMD fails with following exception:

```
sh scripts/build.sh 

> react-router@1.0.0-rc1 build /home/p/workspace/react-router
> babel ./modules -d lib --ignore '__tests__'

ReferenceError: Unknown plugin "object-assign"
    at PluginManager.subnormaliseString (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:147:13)
    at PluginManager.add (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:190:40)
    at File.buildTransformers (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Object.exports.transform (/usr/local/lib/node_modules/babel/lib/babel/util.js:40:22)
    at Object.exports.compile (/usr/local/lib/node_modules/babel/lib/babel/util.js:49:20)
    at write (/usr/local/lib/node_modules/babel/lib/babel/dir.js:19:21)
    at handleFile (/usr/local/lib/node_modules/babel/lib/babel/dir.js:40:7)
    at /usr/local/lib/node_modules/babel/lib/babel/dir.js:56:9

npm ERR! Linux 3.19.0-28-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! react-router@1.0.0-rc1 build: `babel ./modules -d lib --ignore '__tests__'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-router@1.0.0-rc1 build script 'babel ./modules -d lib --ignore '__tests__''.
npm ERR! This is most likely a problem with the react-router package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel ./modules -d lib --ignore '__tests__'
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-router
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/p/workspace/react-router/npm-debug.log

> react-router@1.0.0-rc1 build-umd /home/p/workspace/react-router
> NODE_ENV=production webpack modules/index.js umd/ReactRouter.js

Hash: e108eba89726caba9309
Version: webpack 1.12.2
Time: 224ms
    + 1 hidden modules

ERROR in Loader /home/p/node_modules/babel/index.js didn't return a function

> react-router@1.0.0-rc1 build-min /home/p/workspace/react-router
> NODE_ENV=production webpack -p modules/index.js umd/ReactRouter.min.js

Hash: cd11b0acc36c53c392ce
Version: webpack 1.12.2
Time: 235ms
    + 1 hidden modules

ERROR in Loader /home/p/node_modules/babel/index.js didn't return a function
gzip: umd/ReactRouter.min.js: No such file or directory
gzipped, the UMD build is 0 bytes

```

**Comment by knowbody** [comment]
You need to run `npm install` before:

```sh
npm install && sh scripts/build.sh
```
