### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by carlitux** [rackt/react-router#2158]
I am getting this error when trying to render on server. Here is the complete traceback.

  TypeError: Cannot read property 'match' of undefined
      at Object.matchPattern (/Users/carlitux/Projects/djarana/node_modules/react-router/lib/PatternUtils.js:107:23)
      at matchRouteDeep (/Users/carlitux/Projects/djarana/node_modules/react-router/lib/matchRoutes.js:60:37)
      at /Users/carlitux/Projects/djarana/node_modules/react-router/lib/matchRoutes.js:127:5
      at next (/Users/carlitux/Projects/djarana/node_modules/react-router/lib/AsyncUtils.js:20:12)
      at Object.loopAsync (/Users/carlitux/Projects/djarana/node_modules/react-router/lib/AsyncUtils.js:26:3)
      at Object.matchRoutes [as default] (/Users/carlitux/Projects/djarana/node_modules/react-router/lib/matchRoutes.js:126:15)
      at Object.match (/Users/carlitux/Projects/djarana/node_modules/react-router/lib/useRoutes.js:82:33)
      at match (/Users/carlitux/Projects/djarana/node_modules/react-router/lib/match.js:38:17)

**Comment by carlitux** [comment]
I found the error!

**Comment by bradbumbalough** [comment]
If anyone else came across this error (as I did), the problem was that I was not using `history.createLocation` when assigning the `req.url` location to my server router.

**Comment by carlitux** [comment]
@bradbumbalough yeah. That was my error, too.

**Comment by oscar-g** [comment]
Fixed my error, too.

We should update the docs

**Comment by bradbumbalough** [comment]
@oscar-g actually it seems the docs are correct. The API for the `match()` changed since `1.0.0-rc1` in `master`. So if you need to use the docs from the [`1.0.0-rc1` tag](https://github.com/rackt/react-router/tree/v1.0.0-rc1/docs).

**Comment by oscar-g** [comment]
You're right, I'm on an earlier react-router version looking at the docs on master!
