### ISSUE TITLE
[minor bug] If `to` parameter of `IndexLink` is undefined then the exception occurs

### ISSUE THREAD

**Issue by halt-hammerzeit** [rackt/react-router#2744]
If `to` parameter of `IndexLink` is undefined then the exception occurs

```
Unhandled rejection TypeError: Cannot read property 'charAt' of undefined
    at Object.matchPattern (G:\work\webpack-react-isomorphic-render-example\node_modules\react-router\lib\PatternUtils.j
s:104:15)
    at getMatchingRouteIndex (G:\work\webpack-react-isomorphic-render-example\node_modules\react-router\lib\isActive.js:
64:35)
    at routeIsActive (G:\work\webpack-react-isomorphic-render-example\node_modules\react-router\lib\isActive.js:81:11)
    at Object.isActive [as default] (G:\work\webpack-react-isomorphic-render-example\node_modules\react-router\lib\isAct
ive.js:117:8)
    at Object.isActive (G:\work\webpack-react-isomorphic-render-example\node_modules\react-router\lib\useRoutes.js:69:35
)
    at Link.render (G:\work\webpack-react-isomorphic-render-example\node_modules\react-router\lib\Link.js:127:21)
```

**Comment by taion** [comment]
The `prop` is marked `required` for a reason: https://github.com/rackt/react-router/blob/master/modules/Link.js#L55.
