### ISSUE TITLE
What's the difference between RoutingContext and RouterContext?

### ISSUE THREAD

**Issue by samarpanda** [rackt/react-router#2913]
Was trying to use `RouterContext` to render routes in server-side. It didn't work out. 

```txt
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
/Users/samar/Projects/react-router-demo/node_modules/react/node_modules/fbjs/lib/invariant.js:46
    throw error;
    ^

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
    at invariant (/Users/samar/Projects/react-router-demo/node_modules/react/node_modules/fbjs/lib/invariant.js:39:15)
    at instantiateReactComponent (/Users/samar/Projects/react-router-demo/node_modules/react/lib/instantiateReactComponent.js:64:134)
    at /Users/samar/Projects/react-router-demo/node_modules/react/lib/ReactServerRendering.js:41:31
    at ReactServerRenderingTransaction.Mixin.perform (/Users/samar/Projects/react-router-demo/node_modules/react/lib/Transaction.js:136:20)
    at renderToString (/Users/samar/Projects/react-router-demo/node_modules/react/lib/ReactServerRendering.js:40:24)
    at renderApp (server.js:3:23)
    at server.js:35:9
    at /Users/samar/Projects/react-router-demo/node_modules/react-router/lib/match.js:58:5
    at /Users/samar/Projects/react-router-demo/node_modules/react-router/lib/useRoutes.js:120:15
    at done (/Users/samar/Projects/react-router-demo/node_modules/react-router/lib/AsyncUtils.js:49:19)
```

Changing `RouterContext` to `RoutingContext` fixed the problem. So, was wondering what's the difference in both. Or which one should be prefered for server-side rendering of react apps / routers?

**Comment by samarpanda** [comment]
As per the docs [ServerRendering.md](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md) we need to use `RouterContext`

**Comment by taion** [comment]
Use the docs for the version you have installed, not the docs on master which are for the 2.0.0 RCs.
