### ISSUE TITLE
Examples - express server not started

### ISSUE THREAD

**Issue by condemil** [rackt/react-router#3034]
React Router version: 1.0.3 (latest release)
Node version: 5.4.1
Npm version: 3.3.12
OS version: OSX 10.11.2

Steps to reproduce:

	$ git clone --branch v1.0.3 https://github.com/rackt/react-router.git
	$ cd react-router
	$ npm install
	$ npm start

Expected result: Express server is launched

Got result:

	events.js:141
	      throw er; // Unhandled 'error' event
	      ^

	Error: listen EADDRINUSE :::8080
	    at Object.exports._errnoException (util.js:856:11)
	    at exports._exceptionWithHostPort (util.js:879:20)
	    at Server._listen2 (net.js:1236:14)
	    at listen (net.js:1272:10)
	    at Server.listen (net.js:1368:5)
	    at EventEmitter.listen (/Users/ph/Projects/react/react-router/node_modules/express/lib/application.js:617:24)
	    at Object.<anonymous> (/Users/ph/Projects/react/react-router/examples/server.js:27:5)
	    at Module._compile (module.js:397:26)
	    at Object.Module._extensions..js (module.js:404:10)
	    at Module.load (module.js:343:32)

**Comment by condemil** [comment]
My fault, port is in use.
