### ISSUE TITLE
Incorrectly throwing Invariant Violation: Unrecognised route configuration element for React.Route

### ISSUE THREAD

**Issue by grrowl** [rackt/react-router#731]
I'm not 100% sure if this is `react-router`-specific or a webpack/node.js/`require()` error, but when running a pre-compiled `routes.jsx` to run on the server, the following invariant error is thrown:

```Error: Invariant Violation: Unrecognized route configuration element "<Route>"
    at invariant (/Users/tom/Documents/experiments/eager-rendering-react-webpack-test/node_modules/react/lib/invariant.js:42:15)
    at createRoute (/Users/tom/Documents/experiments/eager-rendering-react-webpack-test/node_modules/react-router/modules/utils/createRoutesFromChildren.js:53:3)```

~~During debug, I noticed the console.log result of `require('react-router').Route` is `function (){return t.apply(this,arguments)}`; 
whereas within the react-router code itself the result of `Router.Route` is~~ this was due to React.Router being logged pre-`React.createElement()`.

Commenting out the following code at `react-router/modules/utils/createRoutesFromChildren.js:48` allows the render to continue without problem (for any route — they match as normal):

```js
invariant(
    CONFIG_ELEMENT_TYPES.indexOf(type) !== -1,
    'Unrecognized route configuration element "<%s>"',
    componentName
  );
```

[Here's a pastebin of the first 200 lines of compiled code](http://pastebin.com/yM87e4MQ). Notably, lines 17–20 looks standard.

Any ideas?

**Comment by mjackson** [comment]
@grrowl This code is removed on master.

**Comment by grrowl** [comment]
Best news of the day. Thanks for the prompt reply.
