### ISSUE TITLE
error running examples

### ISSUE THREAD

**Issue by ilkosta** [rackt/react-router#881]
with node v0.12.0:

#npm run examples

> react-router@0.12.4 examples /home/costa/pkg/js/react/react-router
> webpack-dev-server --config examples/webpack.config.js --no-info --content-base examples

module.js:338
    throw err;
          ^
Error: Cannot find module './lib/'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/costa/pkg/js/react/react-router/node_modules/qs/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by jas** [comment]
Seems `./lib` is missing in the `qs` module. I would try running `npm cache clean` to clear npm's cache before running `npm install` in the `examples` directory.

```
cd examples
rm -rf node_modules
npm cache clean
npm install
npm run examples
```

**Comment by ilkosta** [comment]
thanks, it work!
